Update pipeline.yml

diff --git a/.bluemix/pipeline.yml b/.bluemix/pipeline.yml
--- a/.bluemix/pipeline.yml
+++ b/.bluemix/pipeline.yml
@@ -63,7 +63,7 @@ stages:
       #GIT_HASH=$(git rev-parse HEAD)
       GIT_CC_HASH=$(date +%s)
       GIT_HASH=$(date +%s)
-      export MONGO_SERVICE_INSTANCE_NAME="PostalSCM-MongoDB-qa"
+      export MONGO_SERVICE_INSTANCE_NAME="ibp-mongo-via-tc"
       # detect_exit - will update the IBP service with the error or success of your postal deployment
        detect_exit()
       {
@@ -143,6 +143,15 @@ stages:
       cf delete-service "${SERVICE_INSTANCE_NAME}" -f || true                         # delete existing network (if there is one)
       printf "\n--- Creating a new service instance of the IBM Blockchain Platform service ---\n"
       cf create-service ibm-blockchain-5-prod ibm-blockchain-plan-v1-ga1-starter-prod "${SERVICE_INSTANCE_NAME}" # create the network
+      sleep 15                             # give her a second to warm up
+
+      # -----------------------------------------------------------
+      # 1.1. Create a new mongo db service instance (this creates our mongodb service)
+      # -----------------------------------------------------------
+      printf "\n--- Cleaning up any old service instances of the IBM compose for mongodb (its okay if the command belows fails) ---\n"
+      cf delete-service "${MONGO_SERVICE_INSTANCE_NAME}" -f || true                         # delete existing network (if there is one)
+      printf "\n--- Creating a new service instance of the IBM compose for mongo db service ---\n"
+      cf create-service compose-for-mongodb Standard  "${MONGO_SERVICE_INSTANCE_NAME}" # create the db
       sleep 15                             # give her a second to warm up
 
       # -----------------------------------------------------------
